/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type GelPackProduct = {
  _id: string;
  _type: "gelPackProduct";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sku?: string;
  name?: string;
  size?: "Small" | "Medium" | "Large";
  label?: string;
  dimensions?: string;
  weight?: string;
  features?: Array<string>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  order?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type DeliveryTier = {
  _id: string;
  _type: "deliveryTier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  window?: string;
  detail?: string;
  order?: number;
};

export type RequestQuotePage = {
  _id: string;
  _type: "requestQuotePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  formHeading?: string;
  serviceOptions?: Array<string>;
  advancedTechImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  formHeading?: string;
};

export type GelPacksPage = {
  _id: string;
  _type: "gelPacksPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  note?: string;
  wholesaleEyebrow?: string;
};

export type ProductSolutionsPage = {
  _id: string;
  _type: "productSolutionsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  introCopy?: string;
  cctRxHeading?: string;
  cctRxCopy?: string;
  cctRxSlides?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  categories?: Array<{
    name?: string;
    copy?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "productCategory";
    _key: string;
  }>;
  whyStorageEyebrow?: string;
  whyStorageHeading?: string;
  whyStorageBullets?: Array<string>;
  whyStorageCopy?: string;
  whyProfessionals?: Array<{
    title?: string;
    copy?: string;
    _type: "advantage";
    _key: string;
  }>;
};

export type WarehousePage = {
  _id: string;
  _type: "warehousePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  introLead?: string;
  introCopy?: string;
  capabilities?: Array<{
    name?: string;
    copy?: string;
    _type: "capability";
    _key: string;
  }>;
  storageHeading?: string;
  storageCopy?: string;
  storageImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  advancedTechImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type DeliveryTierReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "deliveryTier";
};

export type DeliveryPage = {
  _id: string;
  _type: "deliveryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  introHeading?: string;
  introCopy?: string;
  whiteGloveHeading?: string;
  whiteGloveCopy?: string;
  deliveryTiers?: Array<
    {
      _key: string;
    } & DeliveryTierReference
  >;
  optionsHeading?: string;
  deliveryOptions?: Array<{
    name?: string;
    detail?: string;
    _type: "deliveryOption";
    _key: string;
  }>;
  closingCopy?: string;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  stats?: Array<
    {
      _key: string;
    } & StatItem
  >;
  categoriesHeading?: string;
  categories?: Array<{
    name?: string;
    href?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    _type: "serviceCategory";
    _key: string;
  }>;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  title?: string;
  mission?: string;
  vision?: string;
  advancedTechImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroStats?: Array<
    {
      _key: string;
    } & StatItem
  >;
  primaryCtaLabel?: string;
  secondaryCtaLabel?: string;
  storageHeading?: string;
  storageCopy?: string;
  productsHeading?: string;
  productsCopy?: string;
  whoWeAreHeading?: string;
  whoWeAreCopy?: string;
  whoWeAreImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  offerHeading?: string;
  offerCopy?: string;
  offerItems?: Array<{
    name?: string;
    copy?: string;
    icon?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    href?: string;
    _type: "offerItem";
    _key: string;
  }>;
  clientsHeading?: string;
  clients?: Array<
    {
      _key: string;
    } & ClientLogo
  >;
  advancedTechImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  testimonialIntro?: string;
  testimonialQuoteParts?: Array<string>;
  testimonialAttribution?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  shortName?: string;
  tagline?: string;
  subhead?: string;
  phone?: string;
  phoneHref?: string;
  email?: string;
  address?: {
    line1?: string;
    line2?: string;
  };
  social?: {
    facebook?: string;
    x?: string;
    instagram?: string;
  };
  navItems?: Array<
    {
      _key: string;
    } & NavLink
  >;
  footerNavItems?: Array<
    {
      _key: string;
    } & NavChildLink
  >;
  credentials?: Array<
    {
      _key: string;
    } & CredentialItem
  >;
  complianceBand?: {
    eyebrow?: string;
    heading?: string;
    copy?: string;
  };
  getInTouch?: {
    eyebrow?: string;
    heading?: string;
    copy?: string;
    formHeading?: string;
  };
};

export type ClientLogo = {
  _type: "clientLogo";
  name?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type CredentialItem = {
  _type: "credentialItem";
  icon?: "truck" | "shield-check" | "scan-barcode" | "badge-check";
  label?: string;
  detail?: string;
};

export type StatItem = {
  _type: "statItem";
  value?: string;
  unit?: string;
  label?: string;
  copy?: string;
};

export type NavLink = {
  _type: "navLink";
  label?: string;
  href?: string;
  children?: Array<
    {
      _key: string;
    } & NavChildLink
  >;
};

export type NavChildLink = {
  _type: "navChildLink";
  label?: string;
  href?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | GelPackProduct
  | SanityImageCrop
  | SanityImageHotspot
  | DeliveryTier
  | RequestQuotePage
  | ContactPage
  | GelPacksPage
  | ProductSolutionsPage
  | WarehousePage
  | DeliveryTierReference
  | DeliveryPage
  | ServicesPage
  | AboutPage
  | HomePage
  | SiteSettings
  | ClientLogo
  | CredentialItem
  | StatItem
  | NavLink
  | NavChildLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;
